language: nix

matrix:
  include:
    - env: TOXENV=pytest-coq84-py27
    - env: TOXENV=pytest-coq85-py27
    - env: TOXENV=pytest-coq86-py27
    - env: TOXENV=pytest-coq87-py27
    - env: TOXENV=pytest-coq88-py27
    - env: TOXENV=pytest-coq89-py27
    - env: TOXENV=pytest-coq810-py27
    - env: TOXENV=pytest-coqmaster-py27
    - env: TOXENV=pytest-coq84-py36
    - env: TOXENV=pytest-coq85-py36
    - env: TOXENV=pytest-coq86-py36
    - env: TOXENV=pytest-coq87-py36
    - env: TOXENV=pytest-coq88-py36
    - env: TOXENV=pytest-coq89-py36
    - env: TOXENV=pytest-coq810-py36
    - env: TOXENV=pytest-coqmaster-py36
    - env: TOXENV=vim

install:
  - if [[ $TOXENV =~ py27 ]]; then PY=27; else PY=36; fi
  - nix-env -j auto -iA nixpkgs.python${PY}Full nixpkgs.python${PY}Packages.virtualenv nixpkgs.python${PY}Packages.pip
  - virtualenv venv
  - source venv/bin/activate
  - python -m pip install tox

script:
  - which python
  - python --version
  - python -m tox
